### ISSUE TITLE
What is the License for this Project?

### ISSUE THREAD

**Issue by aaronvargas** [owlr-com/SharedContentProviders#5]
This looks like a great project and we'd like to be able to use it. What is the License that it's under?

**Comment by chrisjenx** [comment]
Hey @aaronvargas it still needs a bit of work and testing. It will be Apache 2.0, I'll add that now.

**Comment by chrisjenx** [comment]
Added.

**Comment by aaronvargas** [comment]
Thanks! Much appreciated.
